[package]
name = "autometrics"
version = "0.1.0"
edition = "2021"

[features]
default = ["metrics"]

[dependencies]
const_format = { version = "0.2.30", features = ["rust_1_51"] }
metrics = { version = "0.20.1", optional = true }
autometrics-macros = { path = "./macros" }

[dev-dependencies]
metrics-util = "0.14.0"
mockall = "0.11.3"
