[package]
name = "metrics-attributes"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[features]
default = ["metrics"]

[dependencies]
const_format = { version = "*", features = ["rust_1_51"] }
metrics = { version = "0.20.1", optional = true }
metrics-attributes-macros = { path = "./macros" }

[dev-dependencies]
metrics-util = "0.14.0"
mockall = "0.11.3"
