[package]
name = "metrics-attributes-macros"
version = "0.1.0"
edition = "2021"

[lib]
proc-macro = true

[dependencies]
once_cell = "1.16.0"
proc-macro2 = "1.0.49"
quote = "1.0.23"
syn =  { version = "1.0.107", features = ["extra-traits", "full"] }
